spring:
  devtools:
      restart:
        enabled: true  #设置开启热部署
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/rooms_mng?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
#整合mybatis
mybatis:
  mapper-locations: classpath:sqlmap/*Mapper.xml
  type-aliases-package: com.yff.roomsMng.entitys
#showSql
logging:
  level:
     com.yff.roomsMng.dao: DEBUG